#!/usr/bin/env node
// Embeds web/remote/* into the Mac app (VoxCore/Remote/RemoteWebAssets.swift) as base64,
// so the app serves the phone web app without bundle resources.
//   node scripts/embed-web.mjs          regenerate
//   node scripts/embed-web.mjs --check  exit 1 if the Swift file is stale (used by tests)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const webDir = path.join(root, "web", "remote");
const out = path.join(root, "Packages", "VoxCore", "Sources", "VoxCore", "Remote", "RemoteWebAssets.swift");

export function render() {
  const names = fs.readdirSync(webDir).filter((n) => !n.startsWith(".")).sort();
  const lines = names.map((name) => `        ${JSON.stringify(name)}: ${JSON.stringify(fs.readFileSync(path.join(webDir, name)).toString("base64"))},`);
  return `// GENERATED by scripts/embed-web.mjs from web/remote/. Do not edit; edit web/remote and re-run it.
import Foundation

public enum RemoteWebAssets {
    public static let files: [String: String] = [
${lines.join("\n")}
    ]
}
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const text = render();
  if (process.argv.includes("--check")) {
    const current = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : "";
    if (current !== text) { console.error("RemoteWebAssets.swift is stale: run node scripts/embed-web.mjs"); process.exit(1); }
    console.log("RemoteWebAssets.swift is up to date.");
  } else {
    fs.writeFileSync(out, text);
    console.log(`Wrote ${path.relative(root, out)} (${text.length} bytes)`);
  }
}
